name: Lint

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23.x


      - name: Check Go environment
        run: go version

      - name: Install dependencies
        run: |
          go clean -modcache
          go mod tidy
          go get -v -t ./...

      - name: Build
        run: go build -o backend .